;; (install-elisp-from-emacswiki "ipa.el")
;;modify 2010/10/31 キーバインド変更
;;from Emacsテクニックバイブル
;;ファイルに直接書き込まずにメモをする
(require 'ipa)

;(global-set-key (kbd "C-z i c") 'ipa-cleanup)
;(global-set-key (kbd "C-z i i") 'ipa-insert)
;(global-set-key (kbd "C-z i e") 'ipa-edit)
;(global-set-key (kbd "C-z i j") 'ipa-jump)
;(global-set-key (kbd "C-z i s") 'ipa-show)
;(global-set-key (kbd "C-z i n") 'ipa-next)
;(global-set-key (kbd "C-z i p") 'ipa-previous)
;(global-set-key (kbd "C-z i t") 'ipa-toggle)
;(global-set-key (kbd "C-z i g") 'ipa-go-to-annotation)
;;(global-set-key (kbd "C-z i m l d") 'ipa-move-line-down)
;;(global-set-key (kbd "C-z i m l u") 'ipa-move-line-up)
;;(global-set-key (kbd "C-z i m p d") 'ipa-move-page-down)
;;(global-set-key (kbd "C-z i m p u") 'ipa-move-page-up)
;;(global-set-key (kbd "C-z i m <") 'ipa-move-left)
;;(global-set-key (kbd "C-z i m >") 'ipa-move-right)
;;(global-set-key (kbd "C-z i m m") 'ipa-move)
;;(global-set-key (kbd "C-z i m c") 'ipa-move-cancel)
;;(global-set-key (kbd "C-z i m f") 'ipa-move-finish)
;;(global-set-key (kbd "C-z i m h") 'ipa-move-help)
;(global-set-key (kbd "C-z i m") 'ipa-move)

(global-set-key (vconcat my-prefix [(i) (c)]) 'ipa-cleanup)
(global-set-key (vconcat my-prefix [(i) (i)]) 'ipa-insert)
(global-set-key (vconcat my-prefix [(i) (e)]) 'ipa-edit)
(global-set-key (vconcat my-prefix [(i) (j)]) 'ipa-jump)
(global-set-key (vconcat my-prefix [(i) (s)]) 'ipa-show)
(global-set-key (vconcat my-prefix [(i) (n)]) 'ipa-next)
(global-set-key (vconcat my-prefix [(i) (p)]) 'ipa-previous)
(global-set-key (vconcat my-prefix [(i) (t)]) 'ipa-toggle)
(global-set-key (vconcat my-prefix [(i) (g)]) 'ipa-go-to-annotation)
;(global-set-key (vconcat my-prefix [(i) (m) (l) (d)]) 'ipa-move-line-down)
;(global-set-key (vconcat my-prefix [(i) (m) (l) (u)]) 'ipa-move-line-up)
;(global-set-key (vconcat my-prefix [(i) (m) (p) (d)]) 'ipa-move-page-down)
;(global-set-key (vconcat my-prefix [(i) (m) (p) (u)]) 'ipa-move-page-up)
;(global-set-key (vconcat my-prefix [(i) (m) (<)]) 'ipa-move-left)
;(global-set-key (vconcat my-prefix [(i) (m) (>)]) 'ipa-move-right)
;(global-set-key (vconcat my-prefix [(i) (m) (m)]) 'ipa-move)
;(global-set-key (vconcat my-prefix [(i) (m) (c)]) 'ipa-move-cancel)
;(global-set-key (vconcat my-prefix [(i) (m) (f)]) 'ipa-move-finish)
;(global-set-key (vconcat my-prefix [(i) (m) (h)]) 'ipa-move-help)
(global-set-key (vconcat my-prefix [(i) (m)]) 'ipa-move)
